/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compraEVenda;

public class App {

    public static void main(String[] args) {
        AreaCompras areaCompras = new AreaCompras();
        areaCompras.menuInicial();
    }
}
