/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoArray;

public class App {

    public void aprendendo(){
        
        int[] numeros;
        
        numeros = new int[5];
        
        int[] numeros2 = {1,2,3,4,5};
        
        System.out.println(numeros2[0]);
        System.out.println(numeros2[4]);
        
        numeros2[0] = 90;
        
        System.out.println(numeros2[0]);
        
        System.out.println(numeros2.length);
        
        /*
        for(int i = 0; i< numeros2.length; i++){
            System.out.println(numeros2[i]);
        }
        */
        
        for(int numero : numeros2){
            System.out.println(numero);
        }
    }
    
    public void atividade1(){
        String[] nomes = {"Vithor","Guilherme", "Cleber", "Eduardo", "Thiago"};
        
        nomes[2] = "Jobiscléison";     
        
        for(String nome : nomes){
            System.out.println(nome);
        }
    }
    
    public static void main(String[] args) {
        
    }
}
