/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexao;

import java.sql.Connection;

public class App {
    
    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        if(conexao != null){
            CriarTabela.criarTabelaUsusarios(conexao);
            
            InserirUsuario.inserirUsuario(conexao,"João", "joao@gmail.com");
            InserirUsuario.inserirUsuario(conexao,"Vithor", "vithor@gmail.com");
            
            ListarUsuarios.listarUsuarios(conexao);
            
            conexaoSQLite.desconectar(conexao);
        }
    }
}
