/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoLogin;

import java.sql.Connection;

public class App {
    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        if(conexao != null){
            DeletarUsuario.deletarUsuario(conexao,1);
            DeletarUsuario.deletarUsuario(conexao,2);
            DeletarUsuario.deletarUsuario(conexao,3);
            DeletarUsuario.deletarUsuario(conexao,4);
            DeletarUsuario.deletarUsuario(conexao,5);
            DeletarUsuario.deletarUsuario(conexao,6);
            System.out.println(ListarUsuarios.listarUsuarios(conexao));
            
            
            conexaoSQLite.desconectar(conexao);
        }
    }
}
