/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexao2;

import java.sql.Connection;

public class App {
    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        if(conexao != null){
            CriarTabela.criarTabelaUsuarios(conexao);
            
            InserirUsuario.inserirUsuario(conexao,"Joao", "joao@gmail.com");
            InserirUsuario.inserirUsuario(conexao,"Vithor", "vithor@gmail.com");
                    
            System.out.println("Usuarios apos insercão");
            ListarUsuarios.listarUsuarios(conexao);
            
            System.out.println(" ~ Atualizando usuario com ID 1");
            AtualizarUsuario.atualizarUsuario(conexao, 1, "Novonomerson da Silva", "novoemeiou@gmail.com");
            
            System.out.println("Usuarios após atualizacao:");
            ListarUsuarios.listarUsuarios(conexao);
            
            System.out.println(" ~ Deletando usuario com ID 2");
            DeletarUsuario.deletarUsuario(conexao, 2);
            
            System.out.println("Usuarios apos delecao:");
            ListarUsuarios.listarUsuarios(conexao);
            
            conexaoSQLite.desconectar(conexao);
        }
    }
}
