/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.trabalhoavaliativo.view;

import com.mycompany.trabalhoavaliativo.controller.Main;

/**
 *
 * @author VITHORLEONARDOMELLOS
 */
public class PainelInicial extends javax.swing.JPanel {

    private TelaPrincipal telaPrincipal;
    private String nomeDoUsuario;
    /**
     * Creates new form PainelInicial
     */
    public PainelInicial(TelaPrincipal telaPrincipal, String nomeDoUsuario) {
        initComponents();
        this.nomeDoUsuario = nomeDoUsuario;
        txtBemVindo.setText("Bem vindo <" + nomeDoUsuario + ">");
        this.nomeDoUsuario = nomeDoUsuario;
        this.telaPrincipal = telaPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBemVindo = new javax.swing.JLabel();
        botaoLogout = new javax.swing.JButton();

        txtBemVindo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBemVindo.setText("Bem vindo <nomeDoUsuario> ");

        botaoLogout.setText("Logout");
        botaoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoLogout)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(botaoLogout)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogoutActionPerformed
        // TODO add your handling code here:
        Main.reiniciar(telaPrincipal);
        
    }//GEN-LAST:event_botaoLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoLogout;
    private javax.swing.JLabel txtBemVindo;
    // End of variables declaration//GEN-END:variables
}
