/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gameWar;

public class App {

    public static void main(String[] args) {
        Game gameWar = new Game();
        gameWar.start();
    }
}
