/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aula2;

import java.util.Scanner;

public class App {
    static void print(Object valor){
        System.out.println(valor);
    }
    
    /*
        public String meuNome = "Vithor Leonardo";
        public int minhaIdade = 29;
        public double minhaAltura = 1.60;
        public char minhaInicial = 'V';
        public String getApp(){
        return "Meu nome: " + meuNome + "\nMinha idade: " + minhaIdade + "\nMinha altura: " + minhaAltura + "\nMinha inicial: " + minhaInicial;
        }
        
        */
        static String diasDaSemana(int diaNumero){
            String retorno = "Numero Invalido";
            switch(diaNumero){
                case 1:
                    retorno = "Domingo";
                    break;
                case 2:
                    retorno = "Segunda";
                    break;
                case 3:
                    retorno = "Terca";
                    break;
                case 4:
                    retorno = "Quarta";
                    break;
                case 5:
                    retorno = "Quinta";
                    break;
                case 6:
                    retorno = "Sexta";
                    break;
                case 7:
                    retorno = "Sabado";
                    break;
            }
            return retorno;
        }
                
                
        public static void main(String[] args) {
            Scanner scanner = new Scanner(System.in);
            //System.out.println(new App().getApp());
            print(diasDaSemana(1));
            scanner.close();
            
        }
    //}
}



