/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;

public class App {
            
    public String nome = "Vithor Leonardo"; // Caracteres
    public int idade = 17; // Números Inteiros
    public double altura = 1.65; // Números com decimais
    public boolean setJava = true; // Booleans
    public char letraInicial = 'V'; // Apenas um caracter
    
    
    public String getApp(){
          return "Nome: " + nome + "\nIdade: " + idade + "\nAltura: " + altura;
    }
    
    public double soma(double num1, double num2){
    return num1 + num2;
    }
    
    public static double media(double num1, double num2, double num3){
        return (num1+num2+num3)/3;
    }
    
        public static void main(String[] args) {

    System.out.println(new App().getApp());
    
    System.out.println("Soma de (1|2): " + new App().soma(1,2));
    
    System.out.println("Media de (6|3|9): " + new App().media(6,3,9));
    
    }
}
